/*

CREATE DATABASE notes;

USE notes;

CREATE TABLE nts(
id INT(11) NOT NULL,
title VARCHAR(18) NOT NULL,
content VARCHAR(50) NOT NULL
);

ALTER TABLE nts
    ADD PRIMARY KEY (id);

ALTER TABLE nts
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

ALTER TABLE nts
    MODIFY content TEXT;